### ISSUE TITLE
dedupe address list

### ISSUE THREAD

**Issue by worm-emoji** [contextwtf/lanyard#50]
we currently do not dedupe the address list. including the same address more than once leads to a different merkle root

**Comment by ylukem** [comment]
three possible solutions:

- change user input [dedupe]
- send an error
- send a warning

**Comment by ylukem** [comment]
suggestion from @ryandotsmith:

>you could check for dupes in the JS on the client and then offer a link to de-dupe and then the server would return an error if the list still contained dupes

**Comment by malonehedges** [comment]
resolved in #62

**Comment by worm-emoji** [comment]
resolved in #62
