### ISSUE TITLE
Wrong root on root lookup

### ISSUE THREAD

**Issue by jackqack** [contextwtf/lanyard#66]
Hey, Lanyard is really cool! 

I've been following the [docs](https://lanyard.org/docs) to test the API and it seems to be working incorrectly in one use-case. On the last step I'm getting the wrong root for a given proof. Follow these steps:

1. Create a Merkle tree via `POST https://lanyard.org/api/v1/tree` for 2 addresses: 
```
"unhashedLeaves": [
  "0x0000a240a748224a0602b52814145b7a3ad55ef0",
  "0xd8da6bf26964af9d7eed9e03e53415d37aa96045"
]
```

2. The returned **root** is `0x5919f166e07ad1630daa96e1e96aec2e47a54c2953b116a3a4e54d58f8fb6528`. You can look it up and find the right tree with https://lanyard.org/api/v1/tree?root=0x5919f166e07ad1630daa96e1e96aec2e47a54c2953b116a3a4e54d58f8fb6528.

3. Get a **proof** for the **root** from step 2 and the first **wallet** from step 1: https://lanyard.org/api/v1/proof?root=0x5919f166e07ad1630daa96e1e96aec2e47a54c2953b116a3a4e54d58f8fb6528&unhashedLeaf=0x0000a240a748224a0602b52814145b7a3ad55ef0. The returned proof is: `0x06e120c2c3547c60ee47f712d32e5acf38b35d1cc62e23b055a69bb88284c281`.

4. Then request **root** by providing the **proof** from step 3: https://lanyard.org/api/v1/root?proof=0x06e120c2c3547c60ee47f712d32e5acf38b35d1cc62e23b055a69bb88284c281. The returned **root** is `0x19c1a4d3ab7463f369ad6540d97c96279838e78946eb111251905fbf20645e26`, which is different from the **root** in the step 2.

Is this the bug or am I missing something?

**Comment by ryandotsmith** [comment]
Thank you for the detailed report! You are correct; this is a bug. I believe the issue is that the proof-for-root API uses a SQL query that isn't as precise as we need it to be. For example, if you query for a tree using `["x"]` as a proof query parameter, the query will return all trees that contain `"x"` as a proof item instead of a proof that is exactly `["x"]`.

We are working on a fix for the query.

**Comment by worm-emoji** [comment]
@jackqack Thank you again for reporting this issue. It should now be resolved in production.
